---
# This playbook configures a single-instance SOF-ELK(R) system

- name: Setup a single-instance SOF-ELK system
  hosts: all
  become_method: sudo
  become_user: root

  roles:
    - epel_repo
    - cert_forensics_repo
    - elastic_repo
    - sof-elk_pre
